<?php

namespace Drupal\silfi_triplette\Controller;

use Drupal\Core\Controller\ControllerBase;
use Drupal\silfi_triplette\Triplette;

/**
 * Controller routines for menu example routes.
 *
 * The response of Drupal's HTTP Kernel system's request is generated by
 * a piece of code called the controller.
 *
 * In Drupal 8, we use a controller class
 * for placing those piece of codes in methods which responds to a route.
 *
 * This file will be placed at {module_name}/src/Controller directory. Route
 * entries uses a key '_controller' to define the method called from controller
 * class.
 *
 * @see https://www.drupal.org/docs/8/api/routing-system/introductory-drupal-8-routes-and-controllers-example
 */
class TripletteTestController extends ControllerBase {

  /**
   * Page callback for the simplest introduction menu entry.
   *
   * The controller callback defined menu_examples.routing.yml file,
   * maps the path 'examples/menu-example' to this method.
   *
   * @throws \InvalidArgumentException
   */
  public function testTriplette() {
    $triplette = \Drupal::service('silfi_triplette.triplette_json_data')->getTripletteData();
    $build['content'] = [
      '#theme' => 'triplette_test',
      '#data' => $triplette,
    ];
    $build['#cache']['max-age'] = 60;

    return $build;
  }

}
